CREATE PROCEDURE FI_SP_IncBeneficiario
    @NOME          VARCHAR (50),
    @CPF           VARCHAR (14),
    @CLIENTEID     BIGINT
AS
BEGIN
    INSERT INTO BENEFICIARIOS (NOME, CPF, CLIENTEID)
    VALUES (@NOME, @CPF, @CLIENTEID)

    SELECT SCOPE_IDENTITY() AS NewBeneficiarioID
END